nombre_gimnasio=Gym Osvaldo

archivo_clientes=data/clientes.dat
archivo_productos=data/productos.dat
archivo_membresias=data/membresias.dat
archivo_accesos=data/accesos.dat

carpeta_reportes=reports/
carpeta_backups=backups/

version=1.0
modo_debug=true